### PR TITLE
Installation errors should break the build

### LINKED ISSUE #46: BUILD SUCCESSFUL when the installation fails (i.e. Inconsistent certificates)

### PR DESCRIPTION
**Pull request by tasomaniac**
### The Problem 
The problem was that the build was marked as successful even when the installation failed. 
This was bad for `installDevice` task. But it was even worse for `run` because it runs the old version assuming that the installation was successful.

### Solution 

Our plugin does not really handles errors. Also the `adb` almost always exits with success (code 0) and never writes into error stream.
We should investigate and maybe even report back to Google places where we can make use of error codes. 

But in this specific case (APK installation), it is feasible to look at the output. 

Now, I am searching for `Failure` in the text and break the build with the original failure error code. It looks like this: 

image

Fixes #46

### CODE REVIEW

File: plugin/src/main/groovy/com/novoda/gradle/command/Device.groovy [hunk 1]
```diff
@@ -70,6 +70,6 @@ class Device {
     }
 
     String toString() {
-        getClass().name + [id: id, sdk: sdkVersion(), version: androidVersion(), brand: brand(), manufacturer: manufacturer(), model: model(), country: country(), language: language(), timezone: timezone()]
+        getClass().simpleName + [id: id, sdk: sdkVersion(), version: androidVersion(), brand: brand(), manufacturer: manufacturer(), model: model(), country: country(), language: language(), timezone: timezone()]
```
Comment (tasomaniac) [inline plugin/src/main/groovy/com/novoda/gradle/command/Device.groovy]: Also decided to use `simpleName` here. The name was too verbose. Now it just says `Device` which makes sense.

File: plugin/src/main/groovy/com/novoda/gradle/command/Install.groovy [hunk 2]
```diff
@@ -23,4 +23,12 @@ class Install extends AdbTask {
         customFlags ?: ''
     }
 
+    @Override
+    protected handleCommandOutput(def text) {
+        super.handleCommandOutput(text)
+        def matcher = text =~ /Failure \[(.*?)\]/
```
Comment (devisnik) [inline plugin/src/main/groovy/com/novoda/gradle/command/Install.groovy]: Somewhat hacky, but fine with me as long at it fixes the behaviour.

Comment (tasomaniac) [inline plugin/src/main/groovy/com/novoda/gradle/command/Install.groovy]: I know with Nougat release, Android team did a lot of refactoring in adb. I remember I listened in this [podcast](http://androidbackstage.blogspot.de/2016/07/episode-53-adb-on-adb.html). They know forward exit code and error stream of the command being run on the device when we run `adb shell`. 

Unfortunately `adb install` always succeeds with this message in it. I think I need to open a bug report about this.

Comment (devisnik) [inline plugin/src/main/groovy/com/novoda/gradle/command/Install.groovy]: 👍
