### PR TITLE
Fix nougat install

### LINKED ISSUE #108: The install task is broken on Nougat
The problem is that it simply does not accept the argument `-rd` when r and d are together. `-r -d` works. 

As far as I see, it is only on Nougat (both my Nexus 6 and emulator). It could be because of the many changes/refactorings they did on `adb` on Nougat.

```
Exception occurred while dumping:
java.lang.IllegalArgumentException: No argument expected after "-rd"
        at android.os.ShellCommand.getNextOption(ShellCommand.java:195)
        at com.android.server.pm.PackageManagerShellCommand.makeInstallParams(PackageManagerShellCommand.java:999)
        at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:139)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:94)
        at android.os.ShellCommand.exec(ShellCommand.java:94)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:18167)
        at android.os.Binder.shellCommand(Binder.java:468)
        at android.os.Binder.onTransact(Binder.java:367)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2387)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3143)
        at android.os.Binder.execTransact(Binder.java:565)
```

### PR DESCRIPTION
**Pull request by tasomaniac**
The install task is broken on Nougat devices. 

### Solution
Separate the arguments so that it works on Nougat devices. 

Combining different arguments was not a documented feature. It might be working on some devices, it might be ignored on some devices. Now it throws exception on Nougat devices because Nougat has a complete new implementation for adb shell interaction.

**Note:** Unfortunately again, it was a silent fail. It was trying to run after install fail, when we use `run` tasks.

So I decided to include a code piece that I had on my stash. It checks the exit code and errors accordingly. This feature will only work on Nougat devices but still it is useful for Nougat users.

Here is the output on a failure: 

screen shot 2017-01-11 at 10 12 44 am

This PR fixes #108

### CODE REVIEW

File: plugin/src/main/groovy/com/novoda/gradle/command/Install.groovy [hunk 1]
```diff
@@ -12,7 +12,7 @@ class Install extends AdbTask {
         if (getCustomFlags())
             arguments += getCustomFlags()
 
-        arguments += ['-rd', apkPath]
+        arguments += ['-r', '-d', apkPath]
```
Comment (florianmski) [inline plugin/src/main/groovy/com/novoda/gradle/command/Install.groovy]: 👍

File: plugin/src/main/groovy/com/novoda/gradle/command/AdbTask.groovy [hunk 2]
```diff
@@ -57,8 +57,14 @@ public class AdbTask extends org.gradle.api.DefaultTask {
         def adb = getAdb() ?: resolveFromExtension('adb')
         def deviceId = getDeviceId() ?: resolveFromExtension('deviceId')
         AdbCommand command = [adb: adb, deviceId: deviceId, parameters: parameters]
+
         logger.info "running command: $command"
-        handleCommandOutput(command.execute().text)
+
+        Process process = command.execute()
+        if (process.waitFor() != 0) {
```
Comment (devisnik) [inline plugin/src/main/groovy/com/novoda/gradle/command/AdbTask.groovy]: This is what you mention only works on Nougat? Would be good to add a comment about that then, imho.

Comment (tasomaniac) [inline plugin/src/main/groovy/com/novoda/gradle/command/AdbTask.groovy]: Exactly. But it doesn't change any backward compatibility because it was always `0` before.

Comment (tasomaniac) [inline plugin/src/main/groovy/com/novoda/gradle/command/AdbTask.groovy]: let me open a quick pr adding a comment :+1:
